CREATE TABLE `ly_addon_sign` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `uid` INT(11) UNSIGNED NOT NULL COMMENT 'UID',
  `date` DATE COMMENT '创建时间',
  `title` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '标题',
  `create_time` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '修改时间',
  `sort` INT(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `status` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='签到记录表';
