CREATE TABLE `ly_addon_enquiry` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`uid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户ID',
	`name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '联系方式',
	`mobile` VARCHAR(20) NULL DEFAULT '' COMMENT '手机号',
	`qq` VARCHAR(12) NULL DEFAULT '' COMMENT 'QQ',
	`email` VARCHAR(30) NULL DEFAULT '' COMMENT 'Email',
	`content` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '内容',
	`handle_uid` INT(11) NULL DEFAULT NULL,
	`create_time` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
	`update_time` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '修改时间',
	`status` TINYINT(3) NOT NULL DEFAULT '0' COMMENT '状态',
	PRIMARY KEY (`id`)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='在线留言';
